-- 1. 确保 Schema 存在
CREATE SCHEMA IF NOT EXISTS "admin";

-- 管理员表
CREATE TABLE IF NOT EXISTS "admin"."admin" (
    "created_at"      timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"      timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at"      timestamp(6),
    "id"              int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"        varchar(55) NOT NULL,
    "password"        varchar(100) NOT NULL,
    "nickname"        varchar(55),
    "email"           varchar(55),
    "mobile"          varchar(20),
    "permission_key"  json,
    "disabled_status" int2 NOT NULL DEFAULT 0
    );

-- 创建唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS "uk_username" ON "admin"."admin" ("username");

-- 插入初始数据
INSERT INTO "admin"."admin" ("id", "username", "password")
VALUES (1, 'admin123', '$2a$10$uMJY137kuoJWqa.yEBpU6OE5Yh1lYNtnJPOlewFpnE81rd7C3qlsm');

-- 同步 ID 序列 (防止自动增长冲突)
SELECT setval(pg_get_serial_sequence('"admin"."admin"', 'id'), MAX(id)) FROM "admin"."admin";

-- 创建权限表
CREATE TABLE IF NOT EXISTS "admin"."permission" (
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id"   int8,
    "name"        varchar(55)  NOT NULL,
    "code"        varchar(100),
    "key"         varchar(100) NOT NULL DEFAULT '',
    "type"        int2         NOT NULL DEFAULT 1,
    "level"       int4         NOT NULL,
    "path"        varchar(100),
    "icon"        varchar(100),
    "sort"        int4         NOT NULL DEFAULT 1000,
    "remark"      varchar(100),
    "created_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 💡 树形结构必备索引：加速父子节点查询
CREATE INDEX IF NOT EXISTS "idx_permission_parent_id" ON "admin"."permission" ("parent_id");
-- 💡 唯一性索引：确保权限标识符不重复
CREATE UNIQUE INDEX IF NOT EXISTS "uk_permission_key" ON "admin"."permission" ("key");

-- 插入初始权限数据 (去掉时间，由数据库自动生成)
INSERT INTO "admin"."permission"
("id", "parent_id", "name", "code", "key", "type", "level", "path", "sort")
VALUES
    (1,  NULL, '系统',       NULL, '1',        1, 1, NULL, 1),
    (2,  1,    '权限管理',   NULL, '1-2',      1, 2, '/admin/permission', 2),
    (12, 1,    '权限模板',   NULL, '1-12',     1, 2, '/admin/role', 3),
    (13, 1,    '管理员',     NULL, '1-13',     1, 2, '/admin/admin', 1),
    (14, 1,    '操作日志',   NULL, '1-14',     1, 2, '/admin/opLog', 4),
    (15, 13,   '管理员查询', 'admin:read', '1-13-15', 2, 3, NULL, 1),
    (16, 13,   '管理员创建', 'admin:create', '1-13-16', 2, 3, NULL, 1),
    (17, 13,   '管理员更新', 'admin:update', '1-13-17', 2, 3, NULL, 1),
    (18, 2,    '权限查询',   'permission:read', '1-2-18', 2, 3, NULL, 1),
    (19, 2,    '权限创建',   'permission:create', '1-2-19', 2, 3, NULL, 1),
    (20, 2,    '权限更新',   'permission:update', '1-2-20', 2, 3, NULL, 1),
    (21, 2,    '权限删除',   'permission:delete', '1-2-21', 2, 3, NULL, 1),
    (22, 12,   '权限模板查询', 'role:read', '1-12-22', 2, 3, NULL, 1),
    (23, 12,   '权限模板创建', 'role:create', '1-12-23', 2, 3, NULL, 1),
    (24, 12,   '权限模板更新', 'role:update', '1-12-24', 2, 3, NULL, 1),
    (25, 12,   '权限模板删除', 'role:delete', '1-12-25', 2, 3, NULL, 1),
    (26, 14,   '操作日志查询', 'op_log:read', '1-14-26', 2, 3, NULL, 1),
    (27, 14,   '操作日志导出', 'op_log:export', '1-14-27', 2, 3, NULL, 1),
    (28, NULL, '文件管理全部权限', 'file:all', '28', 2, 1, NULL, 1),
    (29, 1,    '任务管理',   NULL, '1-29',     1, 2, '/admin/asyncJob', 11),
    (30, 29,   '任务查询',   'batch_job:read', '1-29-30', 2, 3, NULL, 1)
;

SELECT setval(pg_get_serial_sequence('"admin"."permission"', 'id'), MAX(id)) FROM "admin"."permission";

-- 管理员 - 权限关联表
CREATE TABLE "admin"."admin_permission" (
    "admin_id" int8 NOT NULL,
    "permission_id" int8 NOT NULL
);

-- 权限模板表
CREATE TABLE IF NOT EXISTS "admin"."role" (
    "id"             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"           varchar(55)  NOT NULL DEFAULT '',
    "permission_key" json,
    "remark"         varchar(100),
    "created_at"     timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"     timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 文件表
CREATE TABLE IF NOT EXISTS "admin"."files" (
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category_id" int8,
    "name"        varchar(100) NOT NULL DEFAULT '',
    "key"         varchar(100) NOT NULL DEFAULT '',
    "hash"        varchar(100) NOT NULL DEFAULT '',
    "type"        varchar(50)  NOT NULL DEFAULT '',
    "mime_type"   varchar(100),
    "size"        int8         NOT NULL DEFAULT 0,
    "remark"      varchar(100),
    "created_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 建议：为常用查询字段添加索引（可选）
CREATE INDEX IF NOT EXISTS "idx_files_key" ON "admin"."files" ("key");
CREATE INDEX IF NOT EXISTS "idx_files_hash" ON "admin"."files" ("hash");

-- 创建文件分类表
CREATE TABLE IF NOT EXISTS "admin"."files_category" (
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        varchar(55)  NOT NULL DEFAULT '',
    "remark"      varchar(100),
    "created_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 创建消息表
CREATE TABLE IF NOT EXISTS "admin"."notice" (
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id"    int8,
    "title"       varchar(100) NOT NULL,
    "content"     varchar(200) NOT NULL,
    "attachments" json,
    "created_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 建议：为发布人添加索引，方便查询某个管理员发布的公告
CREATE INDEX IF NOT EXISTS "idx_notice_admin_id" ON "admin"."notice" ("admin_id");

-- 创建操作日志表
CREATE TABLE IF NOT EXISTS "admin"."op_log" (
    "id"           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "admin_id"     int8,
    "ip"           varchar(100) NOT NULL,
    "method"       varchar(22)  NOT NULL,
    "uri"          varchar(100),
    "params"       text,
    "query_params" text,
    "duration"     int8         NOT NULL,
    "remark"       varchar(100),
    "created_at"   timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"   timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 💡 性能建议：由于日志表查询频繁，建议添加索引
CREATE INDEX IF NOT EXISTS "idx_op_log_admin_id" ON "admin"."op_log" ("admin_id");
CREATE INDEX IF NOT EXISTS "idx_op_log_created_at" ON "admin"."op_log" ("created_at");


